server:
  port: ${vault.port}

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${vault.mariadb_url}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${vault.mariadb_username}
    password: ${vault.mariadb_password}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    org:
      apache:
        coyote:
          http11: error
      hibernate:
        SQL: error
