server:
  port: 9001
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 15s
  rabbitmq:
    host: ${vault.rabbitmq_host}
    port: ${vault.rabbitmq_port}
    username: ${vault.rabbitmq_username}
    password: ${vault.rabbitmq_password}
  datasource:
    url: ${vault.mariadb_url}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${vault.mariadb_username}
    password: ${vault.mariadb_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

rabbit:
  queueName: ${vault.mail_queue_name}
  exchangeName: ${vault.mail_exchange_name}
  routingKey: ${vault.mail_routing_key}
  dlq: ${vault.mail_dlq}
  dlx: ${vault.mail_dlx}
  dlqRoutingKey: ${vault.mail_dlq_routing_key}

logging:
  level:
    org:
      apache:
        coyote:
          http11: info
      hibernate:
        SQL: debug
