server:
  port: 9001
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 15s
  rabbitmq:
    host: ${vault.rabbitmq_host}
    port: ${vault.rabbitmq_port}
    username: ${vault.rabbitmq_username}
    password: ${vault.rabbitmq_password}
  datasource:
    master:
      url: ${vault.master_mariadb_url}
      driver-class-name: org.mariadb.jdbc.Driver
      username: ${vault.master_mariadb_username}
      password: ${vault.master_mariadb_password}
    slave:
      url: ${vault.slave_mariadb_url}
      driver-class-name: org.mariadb.jdbc.Driver
      username: ${vault.slave_mariadb_username}
      password: ${vault.slave_mariadb_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  data:
    redis:
      connect-timeout: 2s
      host: ${vault.redis_host}
      port: ${vault.redis_port}
      timeout: 1s

rabbit:
  queueName: ${vault.recommendation_queue_name}
  exchangeName: ${vault.recommendation_exchange_name}
  routingKey: ${vault.recommendation_routing_key}
  dlq: ${vault.recommendation_dlq}
  dlx: ${vault.recommendation_dlx}
  dlqRoutingKey: ${vault.recommendation_dlq_routing_key}

logging:
  level:
    org:
      apache:
        coyote:
          http11: info
      hibernate:
        SQL: debug
