server:
  port: ${vault.port}

spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: debug
      apache:
        coyote:
          http11: info
      hibernate:
        SQL: debug
