spring:
  config:
    activate:
      on-profile: test

  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000
    url: ${vault.mariadb_url}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${vault.mariadb_username}
    password: ${vault.mariadb_password}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
      host: ${vault.redis_host}
      port: ${vault.redis_port}

  test:
    database:
      replace: none

  sql:
    init:
      mode: always

logging:
  level:
    org:
      apache:
        coyote:
          http11: info
      hibernate:
        SQL: debug
