server:
  port: ${vault.port}

spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    org:
      apache:
        coyote:
          http11: error
      hibernate:
        SQL: error
