server:
  port: 9000
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 15s
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s
        pool:
          type: elastic
          max-idle-time: 15s
          max-life-time: 60s
      default-filters:
        - TokenRelay
        - name: Retry
          args:
            retries: 3
            methods: GET
            series: SERVER_ERROR
            exceptions: java.io.IOException, java.util.concurrent.TimeoutException
            backoff:
              firstBackoff: 50ms
              maxBackOff: 500ms
              factor: 2
              basedOnPreviousValue: false
      mvc:
        routes:
          - id: ingredients-manage-route
            uri: http://localhost:9001
            predicates:
              - Path=/ingredients/**
          - id: refrigerators-route
            uri: http://localhost:9001
            predicates:
              - Path=/refrigerators/**
  #TODO Circuit Breaker, Rate Limiter 관련 설정 추가 (추후 트래픽 테스트하고 추가 예정)
  datasource:
    url: ${MARIADB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${MARIADB_USERNAME}
    password: ${MARIADB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
      connect-timeout: 2s
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 1s

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_PASSWORD}
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

          naver:
            client-id: ${NAVER_ID}
            client-secret: ${NAVER_PASSWORD}
            redirect-uri: ${NAVER_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope:
              - email
            client-name: Naver

          kakao:
            client-id: ${KAKAO_ID}
            client-secret: ${KAKAO_PASSWORD}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - account_email
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secretKey: ${JWT_SECRET_KEY}
  accessExpiration: ${ACCESS_EXPIRATION}
  refreshExpiration: ${REFRESH_EXPIRATION}

logging:
  level:
    org:
      apache:
        coyote:
          http11: debug
      hibernate:
        SQL: debug
