server:
  port: ${vault.port}

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${vault.mariadb_url}
    username: ${vault.mariadb_username}
    password: ${vault.mariadb_password}

logging:
  level:
    org:
      apache:
        coyote:
          http11: error
      hibernate:
        SQL: error
